In [10]:
import pandas as pd
import yfinance as yf

tickers = ['BTC','ETH']
frames = []

for ticker in tickers:
    df = yf.download(tickers=ticker+'-GBP', period='ytd', interval='1d')
    df.sort_index(ascending=False, inplace=True)
    df.reset_index(inplace=True)
    df['Ticker'] = ticker
    frames.append(df)
    
df = pd.concat(frames)
df = pd.melt(df, id_vars=['Date','Ticker'])

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

           Date Ticker variable         value
0    2021-05-13    BTC     Open  3.340852e+04
1    2021-05-12    BTC     Open  4.012150e+04
2    2021-05-11    BTC     Open  3.952041e+04
3    2021-05-10    BTC     Open  4.148773e+04
4    2021-05-09    BTC     Open  4.210039e+04
...         ...    ...      ...           ...
1591 2021-01-05    ETH   Volume  3.047940e+10
1592 2021-01-04    ETH   Volume  4.196150e+10
1593 2021-01-03    ETH   Volume  3.303801e+10
1594 2021-01-02    ETH   Volume  1.443777e+10
1595 2021-01-01    ETH   Volume  9.984639e+09

[1596 rows x 4 columns]

In [7]:
frames[0]

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker
0,2021-05-13,33408.523438,36458.753906,33425.953125,35798.238281,35798.238281,73296027648,BTC
1,2021-05-12,40121.503906,41050.617188,34952.027344,34952.027344,34952.027344,53487328457,BTC
2,2021-05-11,39520.410156,40215.601562,38653.750000,40114.460938,40114.460938,43371337504,BTC
3,2021-05-10,41487.726562,42457.597656,38260.476562,39529.296875,39529.296875,50792816541,BTC
4,2021-05-09,42100.394531,42338.859375,40417.902344,41474.511719,41474.511719,46940392533,BTC
...,...,...,...,...,...,...,...,...
128,2021-01-05,23562.761719,25281.978516,22227.591797,24943.916016,24943.916016,49566767303,BTC
129,2021-01-04,23982.244141,24417.646484,21000.929688,23558.984375,23558.984375,59806524259,BTC
130,2021-01-03,23498.419922,25311.591797,23442.039062,23961.103516,23961.103516,57498151044,BTC
131,2021-01-02,21485.000000,24248.593750,21276.359375,23496.855469,23496.855469,49634597054,BTC
132,2021-01-01,21206.855469,21650.548828,21067.576172,21483.314453,21483.314453,29788839044,BTC